name: JCStress Pre-Integration Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build-java: [11, 16-ea]
        run-java: [8, 11, 16-ea]
        os: [ubuntu-18.04, windows-2019, macos-10.15]
      fail-fast: false
    name: Build JDK ${{ matrix.build-java }}, run JDK ${{ matrix.run-java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up build JDK ${{ matrix.build-java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.build-java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.github/workflows/pre-integration.yml') }}
        restore-keys: ${{ runner.os }}-maven
    - name: Build/test
      run: mvn clean install -T 1C -B --file pom.xml
    - name: Set up run JDK ${{ matrix.run-java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.run-java }}
    - name: Run all tests with "sanity" profile
      run: java -jar tests-all/target/jcstress.jar -m sanity --jvmArgs "-XX:+UseParallelGC"
      if: runner.os == 'Linux'
    - name: Run custom tests with "sanity" profile
      run: java -jar tests-custom/target/jcstress.jar -m sanity --jvmArgs "-XX:+UseParallelGC"
      if: runner.os != 'Linux'
