name: JCStress Pre-Integration Tests

on:
  push:
    branches-ignore:
      - master
      - pr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build-java: [17, 20, 21-ea]
        run-java: [8, 11, 17, 20, 21-ea]
        os: [ubuntu-22.04, windows-2022, macos-11]
      fail-fast: false
    name: Build JDK ${{ matrix.build-java }}, run JDK ${{ matrix.run-java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up build JDK ${{ matrix.build-java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.build-java }}
        cache: maven
        check-latest: true
    - name: Build/test
      run: mvn clean install -T 1C -B --file pom.xml
    - name: Set up run JDK ${{ matrix.run-java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.run-java }}
        check-latest: true
    - name: Run a trial test
      run: java -jar tests-custom/target/jcstress.jar -t UnfencedDekker
