name: JCStress Pre-Integration Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build-java: [11, 16-ea]
        run-java: [8, 11, 13, 15, 16-ea]
        os: [ubuntu-18.04, windows-2019, macos-10.15]
      fail-fast: true
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.build-java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.build-java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.github/workflows/pre-integration.yml') }}
        restore-keys: ${{ runner.os }}-maven
    - name: Build all without tests
      run: mvn clean install -DskipTests -B --file pom.xml
    - name: Run unit tests
      run: mvn test -B --file pom.xml
    - name: Set up JDK ${{ matrix.run-java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.run-java }}
    - name: Run sanity profile
      run: java -jar tests-all/target/jcstress.jar -m sanity
